export const ROOT_URL = process.env.NEXT_PUBLIC_URL || "http://localhost:3000";
export const BACKEND_API_URL =
    process.env.NEXT_PUBLIC_BACKEND_API_URL || "http://api.basecard.org";
/**
 * MiniApp configuration object. Must follow the Farcaster MiniApp specification.
 *
 * @see {@link https://miniapps.farcaster.xyz/docs/guides/publishing}
 */
export const minikitConfig = {
    accountAssociation: {
        header: "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4M2QxNThjYjg2Zjg5OUZmMEIyNzM0RDEwODMyMzVDYTA0NzZFNTc0YSJ9",
        payload: "eyJkb21haW4iOiJtaW5pYXBwLmJhc2VjYXJkLm9yZyJ9",
        signature:
            "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAe-csx_0z0dxGexkP1bWTTK13ZRIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAPhSELIcxQMC9He6VmhtIBncm2etAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBj7BWZdVyJEHTIG1PHGzdh4kh8Ff1rTal573LkA1FS1g5DKNO3U3S-COydNca7Zx3_pWTsDQmTJOlvqevv51yyRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJI",
    },
    miniapp: {
        version: "1",
        name: "BaseCard",
        iconUrl: `${ROOT_URL}/bc-icon.png`,
        homeUrl: `${ROOT_URL}`,
        imageUrl: `${ROOT_URL}/bc-icon.png`,
        buttonTitle: "Launch BaseCard",
        splashImageUrl: `${ROOT_URL}/bc-icon.png`,
        splashBackgroundColor: "#ffffff",
        webhookUrl: `${BACKEND_API_URL}/v1/webhook`,
        subtitle: "Builder Identity on Base",
        description:
            "Stop repeating your pitch. Mint your verified, onchain ID card, BaseCard! And, find people who share your interests.",
        primaryCategory: "social",
        heroImageUrl: `${ROOT_URL}/bc-hero.webp`,
        ogImageUrl: `${ROOT_URL}/bc-embed-image.png`,
        ogTitle: "BaseCard",
        tags: ["social", "basecard", "identity", "earn", "card"],
        embedImageUrl: `${ROOT_URL}/bc-embed-image.png`,
        // TODO: ...
        // tagline
        // ogDescriptionaa
        // metadata in the layout
    },
} as const;
